[project]
name = "senior-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "dagster>=1.13.6",
    "dvc>=3.67.1",
    "isort>=8.0.1",
    "make>=0.1.6.post2",
    "pandas>=3.0.3",
    "pathlib>=1.0.1",
    "python-dotenv>=1.2.2",
]
